stages:
  - deploy

deploy_dags:
  stage: deploy
  tags:
    - k8s-airflow-runner  # <--- Khớp với tag bạn đặt lúc cài Helm
  image: bitnami/kubectl:latest
  variables:
    NAMESPACE: "vlp-tenantdvak01g-wsghwlhlt-data"
    PVC_NAME: "dags-pvc-claim"
    JOB_NAME: "sync-dags-${CI_COMMIT_SHORT_SHA}"
  
  script:
    - echo "🚀 Starting DAG deployment..."
    
    # Tạo Job YAML để chạy trong K8s
    - |
      cat <<EOF > sync-job.yaml
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: ${JOB_NAME}
        namespace: ${NAMESPACE}
      spec:
        ttlSecondsAfterFinished: 60
        template:
          spec:
            containers:
            - name: syncer
              image: alpine/git
              command: ["/bin/sh", "-c"]
              args:
                - |
                  set -e
                  echo "📥 Cloning repo...";
                  # thì có thể phải thay bằng IP: http://gitlab-ci-token:${CI_JOB_TOKEN}@192.168.74.12:30080/${CI_PROJECT_PATH}.git
                  git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}:${CI_SERVER_PORT}/${CI_PROJECT_PATH}.git /tmp/repo;
                  
                  
                  echo "📂 Copying new DAGs...";
                  cd /tmp/repo
                  cp -a . /mnt/dags/
                  echo "📋 List files in PVC (Debug):"
                  ls -R /mnt/dags 
                  echo "✅ Done!";
              volumeMounts:
              - name: airflow-storage
                mountPath: /mnt/dags
            restartPolicy: Never
            volumes:
            - name: airflow-storage
              persistentVolumeClaim:
                claimName: ${PVC_NAME}
      EOF

    # Apply Job vào K8s
    - kubectl apply -f sync-job.yaml
    
    - kubectl delete job ${JOB_NAME} -n ${NAMESPACE} --ignore-not-found=true

    # Chờ Job chạy xong (Timeout 2 phút)
    - echo "⏳ Waiting for sync job..."
    - kubectl wait --for=condition=complete job/${JOB_NAME} -n ${NAMESPACE} --timeout=120s
    
    # Dọn dẹp Job
    - kubectl delete job ${JOB_NAME} -n ${NAMESPACE}
